---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(here)
```

```{r}
here::here()
```

```{r}
#Reading in the cleaned data
cbd_admissions <- read_csv(here("clean_data/cerebrovascular_disease_admissions.csv"))
respiratory_admissions <- read_csv(here("clean_data/respiratory_disease_hospital_admissions.csv"))
chd_admissions <- read_csv(here("clean_data/coronary_heart_disease_admissions.csv"))
ddd_admissions <- read_csv(here("clean_data/disease_digestive_system_admissions.csv"))
cancer_admissions <- read_csv(here("clean_data/cancer_admissions.csv"))
```

```{r}
#Checking for missing values across all columns
cbd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
cbd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
cbd_admissions <- cbd_admissions %>% 
  drop_na()
```

```{r}
cbd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
respiratory_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
respiratory_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
respiratory_admissions <- respiratory_admissions %>% 
  drop_na()
```

```{r}
respiratory_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
chd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
chd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
chd_admissions <- chd_admissions %>% 
  drop_na()
```

```{r}
chd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
ddd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
ddd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
ddd_admissions <- ddd_admissions %>% 
  drop_na()
```

```{r}
ddd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```

```{r}
#Checking for missing values across all columns
cancer_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```
```{r}
#Show which areas the missing values are coming from
cancer_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
cancer_admissions <- cancer_admissions %>% 
  drop_na()
```

```{r}
cancer_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```
```{r}
#Filtering datasets to show total for Scotland as a whole over the years
cancer_admissions_scotland <- cancer_admissions %>% 
  filter(reference_area == "Scotland") 

ddd_admissions_scotland <- ddd_admissions %>% 
  filter(reference_area == "Scotland") 

chd_admissions_scotland <- chd_admissions %>% 
  filter(reference_area == "Scotland") 

respiratory_admissions_scotland <- respiratory_admissions %>% 
  filter(reference_area == "Scotland") 

cbd_admissions_scotland <- cbd_admissions %>% 
  filter(reference_area == "Scotland") 
```


```{r}
#Creating a plot of all the hospital admissions
ggplot(cancer_admissions_scotland, aes(x = year, y = admissions_count, group = reference_area)) +
  geom_line(aes(color = "Cancer")) +
  geom_line(data = respiratory_admissions_scotland, aes(group = reference_area, color = "Respiratory Disease")) +
  geom_line(data = ddd_admissions_scotland, aes(group = reference_area, color = "Disease of the Digestive System")) +
  geom_line(data = cbd_admissions_scotland, aes(group = reference_area, color = "Cerebrovascular Disease")) +
  geom_line(data = chd_admissions_scotland, aes(group = reference_area, color = "Coronary Heart Disease")) +
  labs(title = "Hospital Admissions by Long Term Condition",
       subtitle = "2002 - 2012",
       x = "Year",
       y = "Admissions Count",
       color = "Hospital Admissions") +
  scale_x_continuous(breaks = c(2002:2012)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000, 175000))
```


