---
title: "R Notebook"
output: html_notebook
---

# Link to the raw data:-
# https://statistics.gov.scot/resource?uri=http%3A%2F%2Fstatistics.gov.scot%2Fdata%2Fgeneral-health-sscq

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(here)
```

```{r}
here::here()
```

```{r}
#Reading in the cleaned data
general_health <- read_csv(here("clean_data/general_health.csv"))

```

```{r}
#Checking for missing values across all columns
general_health %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#16023 missing dates in date code column
```

```{r}
#Show which areas the missing values are coming from
general_health %>% 
  filter(is.na(date_code))
```


```{r}
#Checking for unique years in date code column
dates_list <- 
  unique(general_health$date_code)

dates_list

#class(dates_list)

#The data ranges from 2012 - 2019
```



```{r}
#Checking for unique phrases in limiting condition column
limiting_condition <- 
  unique(general_health$limiting_long_term_physical_or_mental_health_condition)

limiting_condition
```

```{r}
#Changing reponses as follows:-
#Limiting condition = y
#No limiting condition = n
general_health <- general_health %>% 
  mutate(
    limiting_long_term_physical_or_mental_health_condition = if_else(limiting_long_term_physical_or_mental_health_condition == "Limiting condition", "Y", limiting_long_term_physical_or_mental_health_condition),
    limiting_long_term_physical_or_mental_health_condition = if_else(limiting_long_term_physical_or_mental_health_condition == "No limiting condition", "N", limiting_long_term_physical_or_mental_health_condition)
  )
```


```{r}
#Checking for unique phrases in self assessment column
self_assessment <- 
  unique(general_health$self_assessed_general_health)

self_assessment
```

```{r}
#Removing missing values
general_health <- general_health %>% 
  drop_na()
```


```{r}
general_health %>% 
  #filtering to remove "All" in limiting_long_term_physical_or_mental_health_condition column to show the terms "limiting condition" and "no limiting condition"
  filter(!limiting_long_term_physical_or_mental_health_condition == "All") %>% 
 # mutate(ratio)
  ggplot() +
  geom_col(aes(x = limiting_long_term_physical_or_mental_health_condition, y = value, fill = self_assessed_general_health)) +
  facet_grid(~date_code) +
  labs(title = "Self Assessed General Health",
       subtitle = "2012 - 2019",
       x = "Limiting Long Term Physical or Mental Health Condition",
       y = "Count",
       fill = "Self Assessed General Health") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
general_health %>% 
  #filtering to remove "All" in limiting_long_term_physical_or_mental_health_condition column
  filter(!age == "All") %>% 
    #filtering to remove "All" in limiting_long_term_physical_or_mental_health_condition column 
  ggplot() +
  geom_bar(aes(x = limiting_long_term_physical_or_mental_health_condition, fill = self_assessed_general_health)) +
  facet_grid(~age) +
  labs(title = "Self Assessed General Health",
       subtitle = "2012 - 2019",
       x = "Limiting Long Term Physical or Mental Health Condition",
       y = "Count",
       fill = "Self Assessed General Health") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
general_health_limiting_conditions_male <- general_health %>% 
  #filter(limiting_long_term_physical_or_mental_health_condition == "Y") %>% 
  select(-household_type, -type_of_tenure, -age, -feature_code, -units) %>% 
  group_by(gender, date_code, measurement, value) %>% 
  summarise() %>% 
  filter(gender == "Male") %>% 
  filter(measurement == "Percent") %>% 
  group_by(date_code, measurement) %>% 
  summarise(mean_percentage = mean(value))

general_health_limiting_conditions_female <- general_health %>% 
  #filter(limiting_long_term_physical_or_mental_health_condition == "Y") %>% 
  select(-household_type, -type_of_tenure, -age, -feature_code, -units) %>% 
  group_by(gender, date_code, measurement, value) %>% 
  summarise() %>% 
  filter(gender == "Female") %>% 
  filter(measurement == "Percent") %>% 
  group_by(date_code, measurement) %>% 
  summarise(mean_percentage = mean(value))

  ggplot(general_health_limiting_conditions_male, aes(x = date_code, y = mean_percentage, group = measurement)) +
    geom_line() +
  geom_line(aes(colour = "Male")) +
    geom_line(data =general_health_limiting_conditions_female, aes(group = measurement, colour = "Female")) +
     labs(title = "Self Assessed General Health in Scotland",
       subtitle = "2012 - 2019",
       x = "Year",
       y = "Mean Self Assessment Value (Percent)",
       colour = "Gender") +
    scale_x_continuous(breaks = c(2012:2019))
```

