---
title: "R Notebook"
output: html_notebook
---
```{r}
# Link to the raw data:- https://statistics.gov.scot/resource?uri=http%3A%2F%2Fstatistics.gov.scot%2Fdata%2Fhospital-admissions
```


```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(here)
```

```{r}
here::here()
```

```{r}
#Reading in the cleaned data
cbd_admissions <- read_csv(here("r_dashboard/clean_data/cerebrovascular_disease_admissions.csv"))
respiratory_admissions <- read_csv(here("r_dashboard/clean_data/respiratory_disease_hospital_admissions.csv"))
chd_admissions <- read_csv(here("r_dashboard/clean_data/coronary_heart_disease_admissions.csv"))
ddd_admissions <- read_csv(here("r_dashboard/clean_data/disease_digestive_system_admissions.csv"))
cancer_admissions <- read_csv(here("r_dashboard/clean_data/cancer_admissions.csv"))
longterm_conditions_all <- read_csv(here("r_dashboard/clean_data/longterm_conditions_all.csv"))
```

```{r}
#Checking for missing values across all columns
cbd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
cbd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
cbd_admissions <- cbd_admissions %>% 
  drop_na()
```

```{r}
cbd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
respiratory_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
respiratory_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
respiratory_admissions <- respiratory_admissions %>% 
  drop_na()
```

```{r}
respiratory_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
chd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
chd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
chd_admissions <- chd_admissions %>% 
  drop_na()
```

```{r}
chd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```


```{r}
#Checking for missing values across all columns
ddd_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2573 missing admission numbers
```

```{r}
#Show which areas the missing values are coming from
ddd_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
ddd_admissions <- ddd_admissions %>% 
  drop_na()
```

```{r}
ddd_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```

```{r}
#Checking for missing values across all columns
cancer_admissions %>% 
  summarise(across(.fns = ~sum(is.na(.x))))
#2477 missing admission numbers
```
```{r}
#Show which areas the missing values are coming from
cancer_admissions %>% 
  filter(is.na(admissions_count))
```

```{r}
#Removing missing values from admissions count column
cancer_admissions <- cancer_admissions %>% 
  drop_na()
```

```{r}
cancer_admissions %>% 
  #filtering to show total for Scotland
  filter(reference_area == "Scotland") %>% 
  ggplot() +
  geom_line(aes(x = year, y = admissions_count, group = reference_area))
```
```{r}
#Filtering datasets to show total for Scotland as a whole over the years and combining all datasets
cancer_admissions_scotland <- read_csv("/users/user/group_health_project/hospital_admissions_data/clean_data/cancer_admissions.csv") %>% drop_na() %>% 
  filter(reference_area == "Scotland") %>% 
  mutate(longterm_condition = "cancer")

cbd_admissions_scotland <- read_csv("/users/user/group_health_project/hospital_admissions_data/clean_data/cerebrovascular_disease_admissions.csv")  %>% 
  drop_na() %>% 
  filter(reference_area == "Scotland") %>% 
  mutate(longterm_condition = "cerebrovascular_disease")

chd_admissions_scotland <- read_csv("/users/user/group_health_project/hospital_admissions_data/clean_data/coronary_heart_disease_admissions.csv")  %>% 
  drop_na() %>% 
  filter(reference_area == "Scotland") %>%
    mutate(longterm_condition = "coronary_heart_disease")

ddd_admissions_scotland <- read_csv("/users/user/group_health_project/hospital_admissions_data/clean_data/disease_digestive_system_admissions.csv")  %>% 
  drop_na() %>% 
  filter(reference_area == "Scotland") %>% 
  mutate(longterm_condition = "disease_digestive_system")

respiratory_admissions_scotland <- read_csv("/users/user/group_health_project/hospital_admissions_data/clean_data/respiratory_disease_hospital_admissions.csv")  %>% 
  drop_na() %>% 
  filter(reference_area == "Scotland") %>% 
  mutate(longterm_condition = "respiratory_conditions")

#longterm_conditions_all <- bind_rows(cancer_admissions_scotland, cbd_admissions_scotland, chd_admissions_scotland, ddd_admissions_scotland, respiratory_admissions_scotland)
```


```{r}
#Creating a plot of all the hospital admissions
ggplot(longterm_conditions_all, aes(x = year, y = admissions_count, colour = longterm_condition)) +
  geom_line() +
  labs(title = "Hospital Admissions by Long Term Condition",
       subtitle = "2002 - 2012",
       x = "Year",
       y = "Admissions Count") +
  scale_x_continuous(breaks = c(2002:2012)) +
  scale_color_manual(name = "Longterm Condition",
                     labels = c("Cancer", "Cerebrovascular Disease", "Coronary Heart Disease", "Disease Digestive System", "Respiratory Conditions"),
                     values = c("red", "dark green", "blue", "orange", "purple")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000, 175000))
```